name: joketailor
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - huggingface-hub
  - accelerate
  - datasets
  - numpy
  - pandas
  - peft
  - PyYAML
  - regex
  - requests
  - rich
  - safetensors
  - scikit-learn
  - scipy
  - tokenizers
  - tqdm
  - transformers
  - trl
  - distro
  - bitsandbytes
  - sentence-transformers
  - python-dotenv
  - wandb
  - pytorch-gpu
