channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch==2.5.1
    - huggingface-hub==0.26.2
  - accelerate==1.0.1
  - datasets==3.0.2
  - numpy==2.1.2
  - pandas==2.2.3
  - peft==0.13.2
  - PyYAML==6.0.2
  - regex==2024.9.11
  - requests==2.32.3
  - rich==13.9.3
  - safetensors==0.4.5
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - tokenizers==0.20.1
  - tqdm==4.66.6
  - transformers==4.46.1
  - trl==0.11.4
  - distro==1.9.0
  - bitsandbytes>0.37.0
